/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cosmonaut.glb
Author: Yury Misiyuk (https://sketchfab.com/Tim0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosmonaut-on-a-rocket-e93cbbdb9a2144fb9f63d062566f3e63
Title: Cosmonaut on a rocket
*/

import React, { useRef, useEffect } from "react"
import { useGLTF } from "@react-three/drei"

export default function Cosmonaut(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/cosmonaut.glb")
  useEffect(() => {
    group.current.rotation.x = 0
    group.current.rotation.z = 0
    group.current.rotation.y = -1
    group.current.position.y = -18
  })

  return (
    <group ref={group} {...props} dispose={null} scale={0.15}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="648d44d75b514670a133ce6e37da93c6fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_7">
                    <skinnedMesh
                      name="mesh_0"
                      geometry={nodes.mesh_0.geometry}
                      material={materials.rocket_mtl}
                      skeleton={nodes.mesh_0.skeleton}
                      position={[-160.69, -3.72, -59.55]}
                      scale={0.02}
                    />
                  </group>
                  <group name="Object_9">
                    <skinnedMesh
                      name="mesh_1"
                      geometry={nodes.mesh_1.geometry}
                      material={materials.character_mtl}
                      skeleton={nodes.mesh_1.skeleton}
                      position={[-160.69, -3.72, -59.55]}
                      scale={0.02}
                    />
                  </group>
                  <group name="Object_11">
                    <skinnedMesh
                      name="mesh_2"
                      geometry={nodes.mesh_2.geometry}
                      material={materials.fire_mtl}
                      skeleton={nodes.mesh_2.skeleton}
                      position={[-160.69, -3.72, -59.55]}
                      scale={0.02}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/cosmonaut.glb")
